// license:BSD-3-Clause
// copyright-holders:Salvatore Paxia

#include "emu.h"
#include "keyboard.h"

#include "machine/keyboard.ipp"

// US/ANSI host profile. Alt is a host-only layer, translated on key make:
// its release cannot retrigger a still-held base key. Shift and Control are
// independent ANK inputs. F9 is KB MODE across the M40 and P6066 host maps;
// F12 is reserved for host UI use by the shared m40-ui controller profile.
// Photo legends differ between ANK1402 and ANK1426; BCOS assigns functions.
// Digit PORT_CHARs remain on the keypad for natural-keyboard monitor input.
INPUT_PORTS_START( olivetti_l1_keyboard )
	PORT_START("HOSTALT")
	PORT_BIT(0x01, IP_ACTIVE_HIGH, IPT_OTHER) PORT_CODE(KEYCODE_LALT) PORT_CODE(KEYCODE_RALT) PORT_NAME("Host Alt layer (not sent to M40)")
	PORT_BIT(0xfe, IP_ACTIVE_HIGH, IPT_UNUSED)

	// Numbered by KEYTE1 display field, not an assumed physical/function order.
	// 8049 firmware reports BUS=00 contacts as FD followed by (P2 | C0).
	PORT_START("KEYSWITCHES")
	PORT_CONFNAME(0x03, 0x03, "Key switch 1") PORT_CHANGED_MEMBER(DEVICE_SELF, FUNC(olivetti_l1_keyboard_device::key_switch_changed), 0)
	PORT_CONFSETTING(0x03, "Normal")
	PORT_CONFSETTING(0x01, "Left")
	PORT_CONFSETTING(0x02, "Right")
	PORT_CONFNAME(0x0c, 0x0c, "Key switch 2") PORT_CHANGED_MEMBER(DEVICE_SELF, FUNC(olivetti_l1_keyboard_device::key_switch_changed), 0)
	PORT_CONFSETTING(0x0c, "Normal")
	PORT_CONFSETTING(0x08, "Left")
	PORT_CONFSETTING(0x04, "Right")
	PORT_CONFNAME(0x30, 0x30, "Key switch 3") PORT_CHANGED_MEMBER(DEVICE_SELF, FUNC(olivetti_l1_keyboard_device::key_switch_changed), 0)
	PORT_CONFSETTING(0x30, "Normal")
	PORT_CONFSETTING(0x20, "Left")
	PORT_CONFSETTING(0x10, "Right")
	PORT_BIT(0xc0, IP_ACTIVE_LOW, IPT_UNUSED)

	PORT_START("K0")  // DEL 1..0 -= ~^ BS (digit chars live on the keypad)
	PORT_BIT(0x0001, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("ESC / DEL (06) [Alt+Backspace]") PORT_CHAR(UCHAR_MAMEKEY(DEL))
	PORT_BIT(0x0002, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_1) PORT_NAME("1 ! (01)")
	PORT_BIT(0x0004, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_2) PORT_NAME("2 \" (04)")
	PORT_BIT(0x0008, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_3) PORT_NAME("3 # (07)")
	PORT_BIT(0x0010, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_4) PORT_NAME("4 $ (17)")
	PORT_BIT(0x0020, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_5) PORT_NAME("5 % (1D)")
	PORT_BIT(0x0040, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_6) PORT_NAME("6 & (1E)")
	PORT_BIT(0x0080, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_7) PORT_NAME("7 ' (13)")
	PORT_BIT(0x0100, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_8) PORT_NAME("8 ( (21)")
	PORT_BIT(0x0200, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_9) PORT_NAME("9 ) (24)")
	PORT_BIT(0x0400, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_0) PORT_NAME("0 (2E)")
	PORT_BIT(0x0800, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_MINUS) PORT_NAME("- = (2C)") PORT_CHAR('-')
	PORT_BIT(0x1000, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_EQUALS) PORT_NAME("~ ^ (2B)")
	PORT_BIT(0x2000, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_BACKSPACE) PORT_NAME("BS (31)") PORT_CHAR(8)
	PORT_BIT(0xc000, IP_ACTIVE_HIGH, IPT_UNUSED)

	PORT_START("K1")  // TAB Q..P @' [{ CLEAR RETURN
	PORT_BIT(0x0001, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_TAB) PORT_NAME("TAB (05)") PORT_CHAR(9)
	PORT_BIT(0x0002, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_Q) PORT_CHAR('q')
	PORT_BIT(0x0004, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_W) PORT_CHAR('w')
	PORT_BIT(0x0008, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_E) PORT_CHAR('e')
	PORT_BIT(0x0010, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_R) PORT_CHAR('r')
	PORT_BIT(0x0020, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_T) PORT_CHAR('t')
	PORT_BIT(0x0040, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_Y) PORT_CHAR('y')
	PORT_BIT(0x0080, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_U) PORT_CHAR('u')
	PORT_BIT(0x0100, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_I) PORT_CHAR('i')
	PORT_BIT(0x0200, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_O) PORT_CHAR('o')
	PORT_BIT(0x0400, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_P) PORT_CHAR('p')
	PORT_BIT(0x0800, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_TILDE) PORT_NAME("@ ' (2A)") PORT_CHAR('@')
	PORT_BIT(0x1000, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_OPENBRACE) PORT_NAME("[ { (36)") PORT_CHAR('[')
	PORT_BIT(0x2000, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("CLEAR (37) [Alt+F9]")
	// The alpha RETURN is a plain typing key: the boot prompt and the monitor menus
	// read the KEYPAD terminator (0x61), not this one, so char 13 lives there.
	PORT_BIT(0x4000, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_ENTER) PORT_NAME("RETURN (35)")
	PORT_BIT(0x8000, IP_ACTIVE_HIGH, IPT_UNUSED)

	PORT_START("K2")  // KB-MODE A..L ;+ *: ]}
	PORT_BIT(0x0001, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_F9) PORT_NAME("KB MODE (02)") PORT_CHAR(UCHAR_MAMEKEY(F9))
	PORT_BIT(0x0002, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_A) PORT_CHAR('a')
	PORT_BIT(0x0004, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_S) PORT_CHAR('s')
	PORT_BIT(0x0008, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_D) PORT_CHAR('d')
	PORT_BIT(0x0010, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_F) PORT_CHAR('f')
	PORT_BIT(0x0020, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_G) PORT_CHAR('g')
	PORT_BIT(0x0040, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_H) PORT_CHAR('h')
	PORT_BIT(0x0080, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_J) PORT_CHAR('j')
	PORT_BIT(0x0100, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_K) PORT_CHAR('k')
	PORT_BIT(0x0200, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_L) PORT_CHAR('l')
	PORT_BIT(0x0400, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_COLON) PORT_NAME("; + (2F)") PORT_CHAR(';')
	PORT_BIT(0x0800, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_QUOTE) PORT_NAME("* : (34)") PORT_CHAR(':')
	PORT_BIT(0x1000, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_CLOSEBRACE) PORT_NAME("] } (38)") PORT_CHAR(']')
	PORT_BIT(0xe000, IP_ACTIVE_HIGH, IPT_UNUSED)

	PORT_START("K3")  // SHIFT \ Z..M , . ? CONTROL SPACE
	PORT_BIT(0x0001, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_LSHIFT) PORT_CODE(KEYCODE_RSHIFT) PORT_NAME("SHIFT (6E/76)") PORT_CHAR(UCHAR_SHIFT_1)
	PORT_BIT(0x0002, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_BACKSLASH) PORT_CODE(KEYCODE_BACKSLASH2) PORT_NAME("\\ left-of-Z (0A)") PORT_CHAR('\\')
	PORT_BIT(0x0004, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_Z) PORT_CHAR('z')
	PORT_BIT(0x0008, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_X) PORT_CHAR('x')
	PORT_BIT(0x0010, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_C) PORT_CHAR('c')
	PORT_BIT(0x0020, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_V) PORT_CHAR('v')
	PORT_BIT(0x0040, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_B) PORT_CHAR('b')
	PORT_BIT(0x0080, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_N) PORT_CHAR('n')
	PORT_BIT(0x0100, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_M) PORT_CHAR('m')
	PORT_BIT(0x0200, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_COMMA) PORT_NAME(", (23)") PORT_CHAR(',')
	PORT_BIT(0x0400, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_STOP) PORT_NAME(". (2D)") PORT_CHAR('.')
	PORT_BIT(0x0800, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_SLASH) PORT_NAME("? (29)") PORT_CHAR('?')
	PORT_BIT(0x1000, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_LCONTROL) PORT_CODE(KEYCODE_RCONTROL) PORT_NAME("CONTROL (70/78)") PORT_CHAR(UCHAR_SHIFT_2)
	PORT_BIT(0x2000, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_SPACE) PORT_NAME("SPACE (12)") PORT_CHAR(' ')
	// KEYTE1's 105-key plan explicitly includes LK and expects 6f/77.
	PORT_BIT(0x4000, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_CAPSLOCK) PORT_NAME("LOCK (6F/77)")
	PORT_BIT(0x8000, IP_ACTIVE_HIGH, IPT_UNUSED)

	PORT_START("K4")  // F9/F1..F16/F8, EXIT (its cell = fn row2 pos 7), fn row2 keys
	// (fn row2 names give the BASIC-variant keycaps as hints; the M40 KUSA02
	// legends are unknown except EXIT)
	PORT_BIT(0x0001, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_F1) PORT_NAME("F9/F1 (44)") PORT_CHAR(UCHAR_MAMEKEY(F1))
	PORT_BIT(0x0002, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_F2) PORT_NAME("F10/F2 (46)") PORT_CHAR(UCHAR_MAMEKEY(F2))
	PORT_BIT(0x0004, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_F3) PORT_NAME("F11/F3 (63)") PORT_CHAR(UCHAR_MAMEKEY(F3))
	PORT_BIT(0x0008, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_F4) PORT_NAME("F12/F4 (5B)") PORT_CHAR(UCHAR_MAMEKEY(F4))
	PORT_BIT(0x0010, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_F5) PORT_NAME("F13/F5 (53)") PORT_CHAR(UCHAR_MAMEKEY(F5))
	PORT_BIT(0x0020, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_F6) PORT_NAME("F14/F6 (4B)") PORT_CHAR(UCHAR_MAMEKEY(F6))
	PORT_BIT(0x0040, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_F7) PORT_NAME("F15/F7 (56)") PORT_CHAR(UCHAR_MAMEKEY(F7))
	PORT_BIT(0x0080, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_F8) PORT_NAME("F16/F8 (5A)") PORT_CHAR(UCHAR_MAMEKEY(F8))
	PORT_BIT(0x0100, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("EXIT / SAVE (3D) [Alt+S]")
	PORT_BIT(0x0200, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_SLASH_PAD) PORT_NAME("/ / Backslash (42)")
	PORT_BIT(0x0400, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_ASTERISK) PORT_NAME("* / E^ (43)")
	PORT_BIT(0x0800, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_MINUS_PAD) PORT_NAME("- / ( (41)")
	PORT_BIT(0x1000, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_PLUS_PAD) PORT_NAME("+ / ) (47)")
	PORT_BIT(0x2000, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_PAUSE) PORT_NAME("HALT PGM / ERASE (48) [Alt+H]")
	PORT_BIT(0x4000, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("F19/F20 / LIST (54) [Alt+L]")
	PORT_BIT(0x8000, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_INSERT) PORT_NAME("IC/IL / FETCH (5C)")

	PORT_START("K5")  // keypad; digit CHARs live here (menus read the keypad)
	PORT_BIT(0x0001, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("CLEAR / Keypad * (49) [Alt+C]")
	PORT_BIT(0x0002, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_7_PAD) PORT_CHAR('7')
	PORT_BIT(0x0004, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_8_PAD) PORT_CHAR('8')
	PORT_BIT(0x0008, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_9_PAD) PORT_CHAR('9')
	PORT_BIT(0x0010, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("Keypad comma / - (59) [Alt+Keypad -]")
	PORT_BIT(0x0020, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_4_PAD) PORT_CHAR('4')
	PORT_BIT(0x0040, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_5_PAD) PORT_CHAR('5')
	PORT_BIT(0x0080, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_6_PAD) PORT_CHAR('6')
	PORT_BIT(0x0100, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_DEL_PAD) PORT_NAME("Keypad . (62)") PORT_CHAR(UCHAR_MAMEKEY(DEL_PAD))
	PORT_BIT(0x0200, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_1_PAD) PORT_CHAR('1')
	PORT_BIT(0x0400, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_2_PAD) PORT_CHAR('2')
	PORT_BIT(0x0800, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_3_PAD) PORT_CHAR('3')
	PORT_BIT(0x1000, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_0_PAD) PORT_CHAR('0')
	PORT_BIT(0x2000, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("Keypad 00 (68) [Alt+Keypad 0]")
	PORT_BIT(0x4000, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("Keypad 000 (65) [Alt+Keypad .]")
	PORT_BIT(0x8000, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_ENTER_PAD) PORT_NAME("Keypad ENTER (61)") PORT_CHAR(13) PORT_CHAR(UCHAR_MAMEKEY(ENTER_PAD))

	PORT_START("K6")  // SKIP, DEL LINE, top-right key, right 3x4 block
	PORT_BIT(0x0001, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("SKIP tall (52) [Alt+K]")
	PORT_BIT(0x0002, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_DEL) PORT_NAME("DC/DL / DEL LINE (3B)")
	PORT_BIT(0x0004, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_ESC) PORT_NAME("top-right key (39)")
	PORT_BIT(0x0008, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_END) PORT_NAME("END / RES (51)")
	PORT_BIT(0x0010, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_PGUP) PORT_NAME("|<- back-tab (4C)")
	PORT_BIT(0x0020, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_PGDN) PORT_NAME("->| tab (3A)")
	PORT_BIT(0x0040, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("S3 / AUTO# (5E) [Alt+A]")
	PORT_BIT(0x0080, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_UP) PORT_NAME("Up (4E)") PORT_CHAR(UCHAR_MAMEKEY(UP))
	PORT_BIT(0x0100, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_DOWN) PORT_NAME("Down (3C)") PORT_CHAR(UCHAR_MAMEKEY(DOWN))
	PORT_BIT(0x0200, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_LEFT) PORT_NAME("Left (4A)") PORT_CHAR(UCHAR_MAMEKEY(LEFT))
	PORT_BIT(0x0400, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_RIGHT) PORT_NAME("Right (3E)") PORT_CHAR(UCHAR_MAMEKEY(RIGHT))
	PORT_BIT(0x0800, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("S4 / OLD (66) [Alt+O]")
	PORT_BIT(0x1000, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("S5 / RUN (64) [Alt+R]")
	PORT_BIT(0x2000, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_NAME("H.COPY / DRAW (40) [Alt+D]")
	PORT_BIT(0x4000, IP_ACTIVE_HIGH, IPT_KEYBOARD) PORT_CODE(KEYCODE_HOME) PORT_NAME("HOME / PR ALL/NO PR (3F)")
	PORT_BIT(0x8000, IP_ACTIVE_HIGH, IPT_UNUSED)
INPUT_PORTS_END


olivetti_l1_keyboard_device::olivetti_l1_keyboard_device(const machine_config &mconfig, const char *tag, device_t *owner, uint32_t clock)
	: device_t(mconfig, OLIVETTI_L1_KEYBOARD, tag, owner, clock)
	, device_matrix_keyboard_interface(mconfig, *this, "K0", "K1", "K2", "K3", "K4", "K5", "K6")
	, m_data_cb(*this)
	, m_key_switches(*this, "KEYSWITCHES")
	, m_host_alt(*this, "HOSTALT")
	, m_leds(*this, "m40_kbd_led%u", 0U)
{
}


ioport_constructor olivetti_l1_keyboard_device::device_input_ports() const
{
	return INPUT_PORTS_NAME(olivetti_l1_keyboard);
}


void olivetti_l1_keyboard_device::device_start()
{
}

void olivetti_l1_keyboard_device::command_w(uint8_t data)
{
	// 8049 commands 05-0c and 0f-10 control five P1 outputs. KEYTE1's
	// LED sequence identifies READY, L1, L2 and SHIFT; the fifth is unnamed.
	// P1.4-2 are active low, P1.1-0 active high: odd commands light the
	// indicator and the following even command extinguishes it.
	if (data >= 0x05 && data <= 0x0c)
		m_leds[(data - 0x05) / 2] = BIT(data, 0);
	else if (data == 0x0f || data == 0x10)
		m_leds[4] = BIT(data, 0);
}

void olivetti_l1_keyboard_device::report_key_switches(bool initial)
{
	u8 const status = m_key_switches->read() | 0xc0;
	// Firmware initializes its previous sample to FF, so all-normal at
	// startup produces no report. A later return to Normal does report FF.
	if (initial && status == 0xff)
		return;
	m_data_cb(0xfd);
	m_data_cb(status);
}

INPUT_CHANGED_MEMBER(olivetti_l1_keyboard_device::key_switch_changed)
{
	report_key_switches();
}


void olivetti_l1_keyboard_device::device_reset()
{
	// Firmware INIT writes P1=dc: all five indicators off.
	for (auto &led : m_leds)
		led = 0;
	reset_key_state();
	start_processing(attotime::from_hz(120 * 7)); // 120 complete matrix scans per second
}


uint8_t olivetti_l1_keyboard_device::scancode(uint8_t row, uint8_t column) const
{
	static constexpr uint8_t codes[7][16] =
	{
		{ 0x06,0x01,0x04,0x07,0x17,0x1d,0x1e,0x13,0x21,0x24,0x2e,0x2c,0x2b,0x31,0x00,0x00 },
		{ 0x05,0x03,0x0c,0x08,0x1f,0x11,0x14,0x19,0x25,0x26,0x30,0x2a,0x36,0x37,0x35,0x00 },
		{ 0x02,0x09,0x0f,0x0d,0x18,0x15,0x1b,0x1a,0x28,0x22,0x2f,0x34,0x38,0x00,0x00,0x00 },
		{ 0x6e,0x0a,0x0b,0x0e,0x10,0x20,0x1c,0x16,0x27,0x23,0x2d,0x29,0x70,0x12,0x6f,0x00 },
		{ 0x44,0x46,0x63,0x5b,0x53,0x4b,0x56,0x5a,0x3d,0x42,0x43,0x41,0x47,0x48,0x54,0x5c },
		{ 0x49,0x4f,0x50,0x4d,0x59,0x57,0x58,0x55,0x62,0x5f,0x60,0x5d,0x67,0x68,0x65,0x61 },
		{ 0x52,0x3b,0x39,0x51,0x4c,0x3a,0x5e,0x4e,0x3c,0x4a,0x3e,0x66,0x64,0x40,0x3f,0x00 }
	};

	return codes[row][column];
}


void olivetti_l1_keyboard_device::key_make(uint8_t row, uint8_t column)
{
	u8 code = scancode(row, column);
	if (m_host_alt->read() && code != 0x6e && code != 0x6f && code != 0x70)
	{
		// Select a physical ANK key, never an ASCII macro or an ANK modifier.
		// Mapping on make (not changing the scanned matrix on Alt transitions)
		// avoids a spurious base key when Alt is released before the letter.
		switch (code)
		{
		case 0x02: code = 0x37; break; // Alt+F9: red CLEAR position
		case 0x22: code = 0x54; break; // Alt+L: LIST
		case 0x0f: code = 0x3d; break; // Alt+S: SAVE / EXIT
		case 0x26: code = 0x66; break; // Alt+O: OLD / S4
		case 0x1f: code = 0x64; break; // Alt+R: RUN / S5 (not BCOS RUN/F8)
		case 0x0d: code = 0x40; break; // Alt+D: DRAW / H.COPY
		case 0x09: code = 0x5e; break; // Alt+A: AUTO# / S3
		case 0x28: code = 0x52; break; // Alt+K: SKIP
		case 0x10: code = 0x49; break; // Alt+C: CLEAR
		case 0x1b: code = 0x48; break; // Alt+H: HALT PGM / ERASE
		case 0x31: code = 0x06; break; // Alt+Backspace: alpha ESC / DEL
		case 0x41: code = 0x59; break; // Alt+keypad minus: keypad comma / minus
		case 0x67: code = 0x68; break; // Alt+keypad 0: 00
		case 0x62: code = 0x65; break; // Alt+keypad decimal: 000
		default:   code = 0;    break; // An unassigned Alt combination is silent.
		}
	}
	if (code)
		m_data_cb(code);
}


void olivetti_l1_keyboard_device::key_break(uint8_t row, uint8_t column)
{
	device_matrix_keyboard_interface::key_break(row, column);

	uint8_t const code = scancode(row, column);
	if (code == 0x6e || code == 0x6f || code == 0x70)
		m_data_cb(code + 8);
}


DEFINE_DEVICE_TYPE(OLIVETTI_L1_KEYBOARD, olivetti_l1_keyboard_device, "olivetti_l1_kbd", "Olivetti L1 ANK keyboard")
