// license:BSD-3-Clause
// copyright-holders: Salvatore Paxia
case 82: return 82; // Win + HOME -> Old List
case 54: return 83; // Win + DEL -> Delete line Run
case 55: return 84; // Win + INSERT -> Fetch New
case 83: return 85; // Win + END -> Save Auto
case 39: return 86; // Win + STOP -> Keypad comma
case 50: return 87; // Win + LEFT -> Keypad left paren
case 51: return 88; // Win + RIGHT -> Keypad right paren
case 53: return 89; // Win + DOWN -> Keypad equals
case 52: return 90; // Win + UP -> Keypad up
