// license:BSD-3-Clause
// copyright-holders: Salvatore Paxia
case 82: return 82; // Chord prefix + HOME -> Old List
case 54: return 83; // Chord prefix + DEL -> Delete line Run
case 55: return 84; // Chord prefix + INSERT -> Fetch New
case 83: return 85; // Chord prefix + END -> Save Auto
case 39: return 86; // Chord prefix + STOP -> Keypad comma
case 50: return 87; // Chord prefix + LEFT -> Keypad left paren
case 51: return 88; // Chord prefix + RIGHT -> Keypad right paren
case 53: return 89; // Chord prefix + DOWN -> Keypad equals
case 52: return 90; // Chord prefix + UP -> Keypad up
